import type { Unit } from "../../types";

// ── Life Skills Math (B1): time · money · measurement ──────────────────
// Foundational tier (new "lifeskills" domain, tags math.time/math.money/
// math.measure), distinct from the advanced "math.measurement.*" tier
// that already exists under the "math" domain. Intentional sequencing —
// this unit is the concrete, everyday-object entry point; the advanced
// math.measurement skills go further with the same topics later.
export const lifeSkillsMathUnit: Unit = {
  id: "life-skills-math",
  order: 5,
  title: "Life Skills Math",
  emoji: "🕐",
  world: "garden",
  bigIdea: "Math is everywhere — in clocks, coins, and how big things are.",
  phonicsFocus: "",
  mathFocus: "Time to the hour & half-hour, coins to a dollar, comparing & measuring",
  project: "Make a play store: price three toys and 'buy' them with coins.",
  lessons: [
    {
      id: "lsm-time",
      order: 1,
      title: "Telling Time",
      activities: [
        {
          id: "lsm-time-read-1",
          kind: "math-clock",
          title: "What time is it?",
          blurb: "Read the clock to the hour.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.time"],
          config: {
            mode: "read",
            instruction: "What time does the clock say?",
            hour: 3,
            minute: 0,
            choices: ["2:00", "3:00", "4:00"],
            answerIndex: 1,
          },
        },
        {
          id: "lsm-time-read-2",
          kind: "math-clock",
          title: "Half past the hour",
          blurb: "Read the clock to the half-hour.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.time"],
          config: {
            mode: "read",
            instruction: "What time does the clock say?",
            hour: 7,
            minute: 30,
            choices: ["7:00", "7:30", "8:00"],
            answerIndex: 1,
          },
        },
        {
          id: "lsm-time-set-1",
          kind: "math-clock",
          title: "Make the time",
          blurb: "Move the hands to show the hour.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.time"],
          config: {
            mode: "set",
            instruction: "Make the clock say nine o'clock.",
            targetHour: 9,
            targetMinute: 0,
          },
        },
        {
          id: "lsm-time-set-2",
          kind: "math-clock",
          title: "Half past eleven",
          blurb: "Move the hands to show the half-hour.",
          estMinutes: 8,
          band: "stretch",
          skillTags: ["math.time"],
          config: {
            mode: "set",
            instruction: "Make the clock say half past eleven.",
            targetHour: 11,
            targetMinute: 30,
          },
        },
      ],
    },
    {
      id: "lsm-money",
      order: 2,
      title: "Money & Coins",
      activities: [
        {
          id: "lsm-money-id-1",
          kind: "math-money",
          title: "Find the coin",
          blurb: "Tap the coin that's named.",
          estMinutes: 5,
          band: "ready",
          skillTags: ["math.money"],
          config: {
            mode: "identify",
            instruction: "Tap the dime.",
            coins: ["penny", "nickel", "dime", "quarter"],
            targetCoin: "dime",
          },
        },
        {
          id: "lsm-money-id-2",
          kind: "math-money",
          title: "Find the quarter",
          blurb: "Tap the coin that's named.",
          estMinutes: 5,
          band: "ready",
          skillTags: ["math.money"],
          config: {
            mode: "identify",
            instruction: "Tap the quarter.",
            coins: ["nickel", "dime", "quarter"],
            targetCoin: "quarter",
          },
        },
        {
          id: "lsm-money-count-1",
          kind: "math-money",
          title: "Make 15 cents",
          blurb: "Drop coins to reach the total.",
          estMinutes: 8,
          band: "ready",
          skillTags: ["math.money"],
          config: {
            mode: "count",
            instruction: "Drop coins to make 15 cents.",
            palette: ["penny", "nickel", "dime"],
            targetCents: 15,
          },
        },
        {
          id: "lsm-money-count-2",
          kind: "math-money",
          title: "Make 35 cents",
          blurb: "Drop coins to reach the total.",
          estMinutes: 8,
          band: "ready",
          skillTags: ["math.money"],
          config: {
            mode: "count",
            instruction: "Drop coins to make 35 cents.",
            palette: ["nickel", "dime", "quarter"],
            targetCents: 35,
          },
        },
      ],
    },
    {
      id: "lsm-measure",
      order: 3,
      title: "Measuring",
      activities: [
        {
          id: "lsm-measure-cmp-1",
          kind: "math-measure",
          title: "Which is longest?",
          blurb: "Compare three objects by length.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.measure"],
          config: {
            mode: "compare",
            instruction: "Which one is the longest?",
            attribute: "length",
            question: "most",
            items: [
              { label: "pencil", emoji: "✏️", size: 3 },
              { label: "crayon", emoji: "🖍️", size: 2 },
              { label: "marker", emoji: "🖊️", size: 4 },
            ],
            answerIndex: 2,
          },
        },
        {
          id: "lsm-measure-cmp-2",
          kind: "math-measure",
          title: "Which is heaviest?",
          blurb: "Compare three objects by weight.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.measure"],
          config: {
            mode: "compare",
            instruction: "Which one is the heaviest?",
            attribute: "weight",
            question: "most",
            items: [
              { label: "feather", emoji: "🪶", size: 1 },
              { label: "apple", emoji: "🍎", size: 2 },
              { label: "watermelon", emoji: "🍉", size: 4 },
            ],
            answerIndex: 2,
          },
        },
        {
          id: "lsm-measure-units-1",
          kind: "math-measure",
          title: "How many cubes?",
          blurb: "Measure length in non-standard units.",
          estMinutes: 8,
          band: "ready",
          skillTags: ["math.measure"],
          config: {
            mode: "units",
            instruction: "How many cubes long is the shoe?",
            unit: "cube",
            length: 5,
            choices: [4, 5, 6],
            answerIndex: 1,
          },
        },
        {
          id: "lsm-measure-units-2",
          kind: "math-measure",
          title: "How many paperclips?",
          blurb: "Measure length in a different unit.",
          estMinutes: 8,
          band: "stretch",
          skillTags: ["math.measure"],
          config: {
            mode: "units",
            instruction: "How many paperclips long is the crayon box?",
            unit: "paperclip",
            length: 8,
            choices: [6, 8, 10],
            answerIndex: 1,
          },
        },
      ],
    },
  ],
};
