import type { Unit } from "../../types";

// ── Strand 4: Math ─────────────────────────────────────────────────────
export const mathUnit: Unit = {
  id: "math",
  order: 4,
  title: "Math",
  emoji: "🎪",
  world: "bigtop",
  bigIdea:
    "She already multiplies and reads place value into the hundreds. So we teach forward: multiplication and division, regrouping, fractions, and reasoning. Growing a mathematician, not a calculator.",
  phonicsFocus: "Multiplication → fractions",
  mathFocus: "11 levels",
  project: "Author a two-step word problem for an expedition and the equation that solves it.",
  lessons: [
    {
      id: "math-r1",
      order: 1,
      title: "Equal groups & arrays",
      activities: [
        {
          id: "math-r1-a1",
          kind: "math-array",
          title: "Build the rocket seats",
          blurb: "4 rows of 5. Skip-count to the total.",
          estMinutes: 8,
          band: "ready",
          skillTags: ["math.equal-groups.arrays"],
          config: {
            instruction: "The rocket has 4 rows of seats, 5 seats in each row. Build it, then skip-count one row at a time to find the total.",
            mode: "build",
            rows: 4,
            cols: 5,
            emoji: "🚀",
          },
        },
      ],
    },
    {
      id: "math-r2",
      order: 2,
      title: "Multiplication means equal groups",
      activities: [
        {
          id: "math-r2-a1",
          kind: "math-array",
          title: "Say it three ways",
          blurb: "Array, repeated addition, and 3 x 4 = 12.",
          estMinutes: 8,
          band: "ready",
          skillTags: ["math.mult.meaning"],
          config: {
            instruction: "Build 3 rows of 4. Then say it as 4 + 4 + 4, as 3 x 4, and find the product.",
            mode: "multiply",
            rows: 3,
            cols: 4,
            answer: 12,
            emoji: "🍪",
          },
        },
        {
          id: "math-r2-a2",
          kind: "math-tenframe",
          title: "Skip-count the groups",
          blurb: "Four groups of five, counted on the frames.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.mult.meaning"],
          config: {
            instruction: "Show four groups of five by filling the frames, then count them: 5, 10, 15, 20.",
            mode: "represent",
            target: 20,
            frames: 2,
          },
        },
      ],
    },
    {
      id: "math-r5",
      order: 3,
      title: "Division & fact families",
      activities: [
        {
          id: "math-r5-a1",
          kind: "math-array",
          title: "Share the treasure",
          blurb: "15 gold coins, 3 explorers. How many each?",
          estMinutes: 8,
          band: "ready",
          skillTags: ["math.div.fact-families"],
          config: {
            instruction: "Deal 15 gold coins fairly to 3 explorers. How many does each one get? Then write all four facts this array holds.",
            mode: "divide",
            rows: 3,
            cols: 5,
            answer: 5,
            emoji: "🪙",
          },
        },
      ],
    },
    {
      id: "math-r7",
      order: 4,
      title: "Regrouping (trading tens & ones)",
      activities: [
        {
          id: "math-r7-a1",
          kind: "math-tenframe",
          title: "Trade up",
          blurb: "Combine the ones. Too many? Trade ten for a ten.",
          estMinutes: 10,
          band: "ready",
          skillTags: ["math.regrouping"],
          config: {
            instruction: "Add 7 and 8 on the frames. When the ones fill past ten, trade ten of them for one full ten. That is regrouping.",
            mode: "add",
            target: 7,
            addend: 8,
            frames: 2,
          },
        },
      ],
    },
    {
      id: "math-r8",
      order: 5,
      title: "Fractions: equal parts of a whole",
      activities: [
        {
          id: "math-r8-a1",
          kind: "math-array",
          title: "Area is an array",
          blurb: "Tile the rectangle, then find its area.",
          estMinutes: 8,
          band: "ready",
          skillTags: ["math.geometry.area-arrays", "math.fractions.unit"],
          config: {
            instruction: "Tile this rectangle with unit squares. How many squares cover it? Notice you can multiply the rows by the columns instead of counting each one.",
            mode: "area",
            rows: 3,
            cols: 4,
            answer: 12,
            emoji: "🟦",
          },
        },
        {
          id: "math-r8-a2",
          kind: "math-array",
          title: "Fair shares must be equal",
          blurb: "Split the flatbread into 4 equal parts.",
          estMinutes: 8,
          band: "stretch",
          skillTags: ["math.fractions.unit"],
          config: {
            instruction: "Share the Egyptian flatbread among 4 diggers. Build it as a 1 by 4 row of equal parts, then point to one part: that is 1/4. Would an unequal piece still be 1/4?",
            mode: "area",
            rows: 1,
            cols: 4,
            answer: 4,
            emoji: "🫓",
          },
        },
      ],
    },
  ],
};
