import type { Unit } from "../../types";

export const mathBaselineUnit: Unit = {
  id: "math-baseline",
  order: 0,
  title: "Math — Show what you know",
  emoji: "🌟",
  world: "bigtop",
  bigIdea: "Let's see what you already know about math — there's no wrong here.",
  phonicsFocus: "",
  mathFocus: "A quick, friendly check-in",
  project: "Just play — I'm watching what you've got.",
  checkpoint: "baseline",
  lessons: [
    {
      id: "math-baseline-l1",
      order: 1,
      title: "Show what you know",
      activities: [
        {
          id: "math-baseline-a1",
          kind: "math-array",
          title: "Build the rows",
          blurb: "3 rows of 4. Skip-count to the total.",
          estMinutes: 5,
          band: "ready",
          skillTags: ["math.equal-groups.arrays"],
          config: {
            instruction: "Build 3 rows of 4 stars. Skip-count to find the total.",
            mode: "build",
            rows: 3,
            cols: 4,
            emoji: "⭐",
          },
        },
        {
          id: "math-baseline-a2",
          kind: "math-array",
          title: "Say it three ways",
          blurb: "Array, repeated addition, and the product.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.mult.facts"],
          config: {
            instruction: "Look at 4 rows of 2. Say it as 2 + 2 + 2 + 2, then as 4 x 2, and find the product.",
            mode: "multiply",
            rows: 4,
            cols: 2,
            answer: 8,
            emoji: "🍎",
          },
        },
        {
          id: "math-baseline-a3",
          kind: "math-array",
          title: "Share it fairly",
          blurb: "12 cookies, 4 friends. How many each?",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.div.fact-families"],
          config: {
            instruction: "Share 12 cookies fairly among 4 friends. How many does each friend get?",
            mode: "divide",
            rows: 4,
            cols: 3,
            answer: 3,
            emoji: "🍪",
          },
        },
        {
          id: "math-baseline-a4",
          kind: "math-array",
          title: "Tile the rectangle",
          blurb: "Cover it with unit squares, then count.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.geometry.area-arrays", "math.mult.facts"],
          config: {
            instruction: "Tile this rectangle with unit squares. How many squares cover it?",
            mode: "area",
            rows: 3,
            cols: 4,
            answer: 12,
            emoji: "🟦",
          },
        },
        {
          id: "math-baseline-a5",
          kind: "math-array",
          title: "Fair shares must be equal",
          blurb: "Split the pizza into 5 equal parts.",
          estMinutes: 7,
          band: "ready",
          skillTags: ["math.geometry.area-arrays", "math.mult.facts"],
          config: {
            instruction: "This strip is split into 5 equal parts in a row. How many parts in all?",
            mode: "area",
            rows: 1,
            cols: 5,
            answer: 5,
            emoji: "🍕",
          },
        },
      ],
    },
  ],
};
