import type { Unit } from "../../types";

export const mathBaselineUnit: Unit = {
  id: "math-baseline",
  order: 0,
  title: "Math — Show what you know",
  emoji: "🌟",
  world: "bigtop",
  bigIdea: "Let's see what you already know about math — there's no wrong here.",
  phonicsFocus: "",
  mathFocus: "A quick, friendly check-in",
  project: "Just play — I'm watching what you've got.",
  checkpoint: "baseline",
  lessons: [
    {
      id: "math-baseline-l1",
      order: 1,
      title: "Show what you know",
      activities: [
        {
          id: "math-baseline-a1",
          kind: "math-array",
          title: "Build the rows",
          blurb: "3 rows of 4. Skip-count to the total.",
          estMinutes: 5,
          band: "ready",
          skillTags: ["math.equal-groups.arrays"],
          config: {
            instruction: "Build 3 rows of 4 stars. Skip-count to find the total.",
            mode: "build",
            rows: 3,
            cols: 4,
            emoji: "⭐",
          },
        },
        {
          id: "math-baseline-a2",
          kind: "math-array",
          title: "See it three ways",
          blurb: "Connect the array, repeated addition, and the product.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.mult.meaning"],
          config: {
            instruction: "Look at 4 rows of 2. Connect the model to 2 + 2 + 2 + 2 and 4 x 2, then find the product.",
            mode: "multiply",
            rows: 4,
            cols: 2,
            emoji: "🍎",
          },
        },
        {
          id: "math-baseline-a3",
          kind: "math-array",
          title: "Share it fairly",
          blurb: "12 cookies, 4 friends. How many each?",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.div.fact-families"],
          config: {
            instruction: "Share 12 cookies fairly among 4 friends. How many does each friend get?",
            mode: "divide",
            total: 12,
            groups: 4,
            emoji: "🍪",
          },
        },
        {
          id: "math-baseline-a4",
          kind: "math-array",
          title: "Tile the rectangle",
          blurb: "Cover it with unit squares, then count.",
          estMinutes: 6,
          band: "ready",
          skillTags: ["math.geometry.area-arrays"],
          config: {
            instruction: "Tile this rectangle with unit squares. How many squares cover it?",
            mode: "area",
            rows: 3,
            cols: 4,
            emoji: "🟦",
          },
        },
        {
          id: "math-baseline-a5",
          kind: "math-fraction-bar",
          title: "Show two fourths",
          blurb: "Select 2 of 4 equal pieces.",
          estMinutes: 7,
          band: "stretch",
          skillTags: ["math.fractions.unit"],
          config: {
            instruction: "The bar has 4 equal parts. Select 2 parts to show two fourths.",
            mode: "identify",
            numerator: 2,
            denominator: 4,
          },
        },
      ],
    },
  ],
};
