import type { Unit } from "../../types";

// ── Strand 3: Writing & Composition (the bridge) ───────────────────────
export const writingUnit: Unit = {
  id: "writing",
  order: 3,
  title: "Writing & Composition",
  emoji: "🚀",
  world: "space",
  bigIdea:
    "Her ideas are years ahead of her hand. So composition runs at her thinking level today, scribed or typed, while handwriting climbs its own gentle ladder. She is an author from rung one.",
  phonicsFocus: "Sentence → paragraph → revise",
  mathFocus: "Bridged: ideas first",
  project: "Compose, revise, and \"publish\" a real piece, then read it aloud as the author.",
  lessons: [
    {
      id: "writing-r2",
      order: 1,
      title: "One complete sentence",
      activities: [
        {
          id: "writing-r2-a1",
          kind: "journal-prompt",
          title: "Finish the frame",
          blurb: "You bring the idea. The frame holds the words.",
          estMinutes: 8,
          band: "ready",
          skillTags: [],
          config: {
            prompt: "Tell one true thing about today's expedition. Say it as a whole sentence.",
            drawing: false,
            mode: "compose",
            frames: ["The volcano erupted because ______.", "I learned that ______."],
            wordBank: ["pressure", "magma", "erupted", "lava", "underground"],
            allowModes: ["scribe", "type", "dictate"],
          },
        },
      ],
    },
    {
      id: "writing-r3",
      order: 2,
      title: "Expand a sentence",
      activities: [
        {
          id: "writing-r3-a1",
          kind: "journal-prompt",
          title: "Grow the sentence",
          blurb: "Add a who, a where, a why. Trade a stronger verb.",
          estMinutes: 10,
          band: "ready",
          skillTags: [],
          config: {
            prompt: "Start with \"The boat went on the water.\" Make it richer: add a detail, an adjective, or a stronger verb.",
            drawing: false,
            mode: "compose",
            frames: ["The ______ boat ______ across the ______ water."],
            wordBank: ["little", "raced", "drifted", "crashed", "stormy", "calm", "quickly"],
            allowModes: ["scribe", "type", "dictate"],
          },
        },
      ],
    },
    {
      id: "writing-r5",
      order: 3,
      title: "Three-sentence pieces (narrative, info, opinion)",
      activities: [
        {
          id: "writing-r5-a1",
          kind: "journal-prompt",
          title: "Tiny story",
          blurb: "Beginning, middle, end, in three sentences.",
          estMinutes: 12,
          band: "ready",
          skillTags: [],
          config: {
            prompt: "Tell a tiny story about a volcano with a beginning, a middle, and an end.",
            drawing: false,
            mode: "compose",
            frames: ["First, ______.", "Then, ______.", "Finally, ______."],
            wordBank: ["the ground shook", "smoke poured out", "it erupted", "everyone ran to safety"],
            allowModes: ["scribe", "type", "dictate"],
          },
        },
        {
          id: "writing-r5-a2",
          kind: "journal-prompt",
          title: "I think... because",
          blurb: "Give an opinion and back it with reasons.",
          estMinutes: 10,
          band: "ready",
          skillTags: [],
          config: {
            prompt: "What is the best ocean animal? Tell me what you think and why.",
            drawing: false,
            mode: "compose",
            frames: ["I think ______ is the best ocean animal because ______."],
            wordBank: ["whales", "huge", "gentle", "they sing", "they are smart"],
            allowModes: ["scribe", "type", "dictate"],
          },
        },
      ],
    },
    {
      id: "writing-r6",
      order: 4,
      title: "A short paragraph",
      activities: [
        {
          id: "writing-r6-a1",
          kind: "journal-prompt",
          title: "Topic + three details",
          blurb: "Open with a topic sentence, then stay on one idea.",
          estMinutes: 14,
          band: "ready",
          skillTags: [],
          config: {
            prompt: "Write a short paragraph about whales. Start with a topic sentence, then add three facts you know, all about whales.",
            drawing: false,
            mode: "compose",
            frames: ["Whales are amazing ocean animals.", "First, ______.", "Also, ______.", "Best of all, ______."],
            wordBank: ["biggest animals", "they breathe air", "they sing songs", "they live in pods"],
            allowModes: ["type", "dictate"],
          },
        },
      ],
    },
    {
      id: "writing-r7",
      order: 5,
      title: "Revise & edit",
      activities: [
        {
          id: "writing-r7-a1",
          kind: "journal-prompt",
          title: "Make it stronger",
          blurb: "Swap a weak word. Add a detail. Say why it's better.",
          estMinutes: 12,
          band: "stretch",
          skillTags: [],
          config: {
            prompt: "Here is a draft sentence: \"The volcano was big and it went.\" Make it stronger. Swap a bland word for a livelier one and add one detail. Then say why your change is better.",
            drawing: false,
            mode: "compose",
            frames: ["The ______ volcano ______."],
            wordBank: ["enormous", "erupted", "exploded", "towering", "suddenly"],
            allowModes: ["type", "scribe"],
          },
        },
      ],
    },
  ],
};
