import type { Program } from "../types";

/**
 * Program 01 — Summer Bridge: Kindergarten → 1st Grade (stretch to 2nd).
 * Typed from docs/curriculum/summer-k-to-grade1/. The curriculum docs are the
 * human source of truth; this is the machine representation the app renders.
 * Each unit carries the real weekly theme + phonics/math focus + project; the
 * activities are a curated, skill-tagged sample per week (the full day-by-day
 * seed is generated later — see spec §5). [2nd] focuses are band: "stretch".
 */
export const summerKToGrade1: Program = {
  slug: "summer-k-to-grade1",
  title: "Summer Bridge",
  subtitle: "Kindergarten → 1st Grade",
  ageBand: "Ages 5–6 · just finished K",
  summary:
    "A 10-week, play-balanced summer that walks into 1st grade confident, with 2nd-grade stretch skills already in reach. Decode, don't memorize. Little and often. Warm always.",
  units: [
    {
      id: "u1",
      order: 1,
      title: "Ready, Set, Summer!",
      emoji: "🎒",
      world: "sunshine",
      bigIdea: "All about me. Find our starting line and build the routine.",
      phonicsFocus: "Review short vowels & CVC",
      mathFocus: "Count to 100; compare numbers",
      project: "An \"All About Me\" book",
      checkpoint: "baseline",
      lessons: [
        {
          id: "u1-l1",
          order: 1,
          title: "First day",
          activities: [
            {
              id: "u1-l1-a1",
              kind: "phonics-wordbuild",
              title: "Build a CVC word",
              blurb: "Sound it out, tap the letters.",
              estMinutes: 8,
              band: "ready",
              skillTags: ["phonics.cvc"],
              standardTags: ["CCSS.RF.K.3", "CCSS.RF.1.2"],
              config: {
                focus: "short vowels (CVC)",
                instruction: "Let's build a word! Tap the sounds to spell the picture.",
                tiles: ["c", "a", "t", "s", "u", "n", "p", "i", "g"],
                words: [{ word: "cat", picture: "🐱" }, { word: "sun", picture: "☀️" }, { word: "pig", picture: "🐷" }],
              },
            },
            {
              id: "u1-l1-a2",
              kind: "math-tenframe",
              title: "Show this number",
              blurb: "Fill the ten-frame.",
              estMinutes: 6,
              band: "ready",
              skillTags: ["math.counting"],
              standardTags: ["CCSS.1.NBT.1"],
              config: { instruction: "Can you show 7? Tap to fill the dots.", mode: "represent", target: 7 },
            },
            {
              id: "u1-l1-a3",
              kind: "journal-prompt",
              title: "All about me",
              blurb: "Draw you, then tell us.",
              estMinutes: 10,
              band: "ready",
              skillTags: ["writing.sentence", "habits.stamina"],
              config: { prompt: "Draw your favorite thing about you. Then we'll write about it!", sentenceStarter: "I love that I can…" },
            },
          ],
        },
      ],
    },
    {
      id: "u2",
      order: 2,
      title: "Under the Sea",
      emoji: "🌊",
      world: "ocean",
      bigIdea: "Two letters, one sound. Tens and ones build bigger numbers.",
      phonicsFocus: "Digraphs: sh, ch, th, wh, ck",
      mathFocus: "Place value: tens & ones",
      project: "Ocean-in-a-bottle + a tens/ones reef",
      lessons: [
        {
          id: "u2-l1",
          order: 1,
          title: "Splash in",
          activities: [
            {
              id: "u2-l1-a1",
              kind: "phonics-wordbuild",
              title: "Digraph dive",
              blurb: "sh, ch, th make one sound.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["phonics.digraphs"],
              standardTags: ["CCSS.RF.1.3.a"],
              config: {
                focus: "digraphs sh / ch / th",
                instruction: "Two letters, one sound! Build the word for each picture.",
                tiles: ["sh", "ch", "th", "i", "p", "a", "t", "f", "s"],
                words: [{ word: "ship", picture: "🚢" }, { word: "chip", picture: "🍟" }, { word: "fish", picture: "🐟" }],
              },
            },
            {
              id: "u2-l1-a2",
              kind: "math-tenframe",
              title: "Make a teen",
              blurb: "One full frame and some more.",
              estMinutes: 8,
              band: "ready",
              skillTags: ["math.place-value"],
              standardTags: ["CCSS.1.NBT.2"],
              config: { instruction: "Show 14: fill one ten, then four more.", mode: "represent", target: 14, frames: 2 },
            },
            {
              id: "u2-l1-a3",
              kind: "sightword-game",
              title: "Treasure words",
              blurb: "Catch the words you know.",
              estMinutes: 6,
              band: "ready",
              skillTags: ["reading.sight-words"],
              config: { instruction: "Tap the treasure words: they, was, are.", words: ["they", "was", "are", "with"], decoys: ["thay", "wos", "ar"] },
            },
          ],
        },
      ],
    },
    {
      id: "u3",
      order: 3,
      title: "Bugs & Butterflies",
      emoji: "🐛",
      world: "garden",
      bigIdea: "Blends at the start. Adding by counting on and making ten.",
      phonicsFocus: "Beginning blends (bl, st, gr…)",
      mathFocus: "Addition within 10 → 20",
      project: "A butterfly life-cycle wheel",
      lessons: [
        {
          id: "u3-l1",
          order: 1,
          title: "In the garden",
          activities: [
            {
              id: "u3-l1-a1",
              kind: "phonics-wordbuild",
              title: "Blend it",
              blurb: "Two sounds slide together.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["phonics.blends.initial"],
              standardTags: ["CCSS.RF.1.3.b"],
              config: {
                focus: "beginning blends bl / st / gr",
                instruction: "Slide the two sounds together to start the word.",
                tiles: ["bl", "st", "gr", "o", "p", "a", "r", "e", "m"],
                words: [{ word: "stop", picture: "🛑" }, { word: "grab", picture: "✊" }, { word: "blot", picture: "🔵" }],
              },
            },
            {
              id: "u3-l1-a2",
              kind: "math-tenframe",
              title: "Make ten to add",
              blurb: "9 + 4 by making a ten.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["math.addition"],
              standardTags: ["CCSS.1.OA.6"],
              config: { instruction: "Add 9 and 4. Fill the first frame to make ten, then count on.", mode: "add", target: 9, addend: 4, frames: 2 },
            },
          ],
        },
      ],
    },
    {
      id: "u4",
      order: 4,
      title: "Blast Off!",
      emoji: "🚀",
      world: "space",
      bigIdea: "Blends at the end. Taking away within 20.",
      phonicsFocus: "Ending blends (-nd, -st, -mp…)",
      mathFocus: "Subtraction within 10 → 20",
      project: "Build & launch a paper rocket",
      lessons: [
        {
          id: "u4-l1",
          order: 1,
          title: "Countdown",
          activities: [
            {
              id: "u4-l1-a1",
              kind: "phonics-wordbuild",
              title: "Land the ending",
              blurb: "Blends close the word.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["phonics.blends.final"],
              standardTags: ["CCSS.RF.1.3.b"],
              config: {
                focus: "ending blends -nd / -st / -mp",
                instruction: "Finish each word with the right ending blend.",
                tiles: ["nd", "st", "mp", "ha", "ne", "ju", "la", "be", "fi"],
                words: [{ word: "hand", picture: "✋" }, { word: "nest", picture: "🪺" }, { word: "jump", picture: "🤸" }],
              },
            },
            {
              id: "u4-l1-a2",
              kind: "math-tenframe",
              title: "Blast away",
              blurb: "Take some away.",
              estMinutes: 7,
              band: "ready",
              skillTags: ["math.subtraction"],
              standardTags: ["CCSS.1.OA.6"],
              config: { instruction: "Start with 13. Blast off 5. How many are left?", mode: "represent", target: 8 },
            },
            {
              id: "u4-l1-a3",
              kind: "journal-prompt",
              title: "My rocket",
              blurb: "Where will you fly?",
              estMinutes: 10,
              band: "ready",
              skillTags: ["writing.sentence"],
              config: { prompt: "Draw your rocket. Where is it flying?", sentenceStarter: "My rocket flies to…" },
            },
          ],
        },
      ],
    },
    {
      id: "u5",
      order: 5,
      title: "Growing Garden",
      emoji: "🌱",
      world: "garden",
      bigIdea: "Magic-e makes the vowel say its name. Facts get fluent.",
      phonicsFocus: "Silent-e / long vowels (a_e, i_e…)",
      mathFocus: "Fact fluency + word problems",
      project: "Plant seeds & keep a growth journal",
      checkpoint: "mid",
      lessons: [
        {
          id: "u5-l1",
          order: 1,
          title: "Sprout",
          activities: [
            {
              id: "u5-l1-a1",
              kind: "phonics-wordbuild",
              title: "Magic e",
              blurb: "Add e, the vowel says its name.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["phonics.silent-e"],
              standardTags: ["CCSS.RF.1.3.c"],
              config: {
                focus: "silent-e (a_e, i_e, o_e)",
                instruction: "Add the magic e and hear the vowel say its name!",
                tiles: ["c", "a", "k", "e", "b", "i", "n", "o"],
                words: [{ word: "cake", picture: "🍰" }, { word: "bike", picture: "🚲" }, { word: "bone", picture: "🦴" }],
              },
            },
            {
              id: "u5-l1-a2",
              kind: "sightword-game",
              title: "Garden words",
              blurb: "Pick the real words.",
              estMinutes: 6,
              band: "ready",
              skillTags: ["reading.sight-words"],
              config: { instruction: "Tap the words you can read: have, said, what, were.", words: ["have", "said", "what", "were"], decoys: ["haz", "sed", "wut"] },
            },
          ],
        },
      ],
    },
    {
      id: "u6",
      order: 6,
      title: "Dinosaurs & Long Ago",
      emoji: "🦕",
      world: "bigtop",
      bigIdea: "Vowel teams travel in pairs. Big numbers add up.",
      phonicsFocus: "Vowel teams (ai, ay, ee, ea, oa)",
      mathFocus: "Two-digit addition (no regroup) [2nd stretch]",
      project: "A dino \"dig\" & fossil measuring",
      lessons: [
        {
          id: "u6-l1",
          order: 1,
          title: "The dig",
          activities: [
            {
              id: "u6-l1-a1",
              kind: "phonics-wordbuild",
              title: "Team up the vowels",
              blurb: "Two vowels, one long sound.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["phonics.vowel-teams"],
              standardTags: ["CCSS.RF.1.3.c"],
              config: {
                focus: "vowel teams ai / ee / oa",
                instruction: "Two vowels go walking. Build each word!",
                tiles: ["r", "ai", "n", "b", "ee", "oa", "t", "s", "d"],
                words: [{ word: "rain", picture: "🌧️" }, { word: "bee", picture: "🐝" }, { word: "boat", picture: "⛵" }],
              },
            },
            {
              id: "u6-l1-a2",
              kind: "math-tenframe",
              title: "Big bones add up",
              blurb: "Tens and ones together.",
              estMinutes: 9,
              band: "stretch",
              skillTags: ["math.addition", "math.place-value"],
              standardTags: ["CCSS.1.NBT.4", "CCSS.2.NBT.5"],
              config: { instruction: "Add 12 and 6. Show it on two frames.", mode: "add", target: 12, addend: 6, frames: 2 },
            },
          ],
        },
      ],
    },
    {
      id: "u7",
      order: 7,
      title: "Weather & Seasons",
      emoji: "⛅",
      world: "ocean",
      bigIdea: "Bossy R changes the vowel. Measure and compare.",
      phonicsFocus: "R-controlled (ar, or, er, ir, ur)",
      mathFocus: "Measurement: length & comparing",
      project: "Make a rain gauge + weather chart",
      lessons: [
        {
          id: "u7-l1",
          order: 1,
          title: "Stormy day",
          activities: [
            {
              id: "u7-l1-a1",
              kind: "phonics-wordbuild",
              title: "Bossy R",
              blurb: "R bosses the vowel around.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["phonics.r-controlled"],
              standardTags: ["CCSS.RF.1.3"],
              config: {
                focus: "r-controlled ar / or / ir",
                instruction: "The R is bossy! Build each word.",
                tiles: ["ar", "or", "ir", "c", "f", "b", "d", "n", "t"],
                words: [{ word: "car", picture: "🚗" }, { word: "corn", picture: "🌽" }, { word: "bird", picture: "🐦" }],
              },
            },
            {
              id: "u7-l1-a2",
              kind: "journal-prompt",
              title: "Today's weather",
              blurb: "Look outside and tell us.",
              estMinutes: 8,
              band: "ready",
              skillTags: ["writing.sentence"],
              config: { prompt: "What is the weather today? Draw the sky.", sentenceStarter: "Today it is…" },
            },
          ],
        },
      ],
    },
    {
      id: "u8",
      order: 8,
      title: "My Community & Money",
      emoji: "🏙️",
      world: "bigtop",
      bigIdea: "Gliding vowels. Telling time and counting coins.",
      phonicsFocus: "Diphthongs (oi, oy, ou, ow)",
      mathFocus: "Time (hour/half → 5 min) & coins [2nd stretch]",
      project: "A \"town\" map + pretend store",
      lessons: [
        {
          id: "u8-l1",
          order: 1,
          title: "Around town",
          activities: [
            {
              id: "u8-l1-a1",
              kind: "phonics-wordbuild",
              title: "Gliding sounds",
              blurb: "oi, oy, ou, ow.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["phonics.diphthongs"],
              standardTags: ["CCSS.RF.1.3"],
              config: {
                focus: "diphthongs oi / ou / ow",
                instruction: "These vowels glide! Build each word.",
                tiles: ["oi", "ou", "ow", "c", "n", "l", "d", "c", "w"],
                words: [{ word: "coin", picture: "🪙" }, { word: "cloud", picture: "☁️" }, { word: "cow", picture: "🐄" }],
              },
            },
            {
              id: "u8-l1-a2",
              kind: "sightword-game",
              title: "Shop signs",
              blurb: "Read the store words.",
              estMinutes: 6,
              band: "stretch",
              skillTags: ["reading.sight-words"],
              config: { instruction: "Tap the words: open, buy, your, money.", words: ["open", "buy", "your", "money"], decoys: ["opin", "by", "yor"] },
            },
          ],
        },
      ],
    },
    {
      id: "u9",
      order: 9,
      title: "Animals Around the World",
      emoji: "🌍",
      world: "garden",
      bigIdea: "Endings change words. Shapes and fair shares.",
      phonicsFocus: "Endings -s, -ed, -ing; syllables",
      mathFocus: "Geometry: 2D/3D shapes; halves & fourths",
      project: "A habitat diorama",
      lessons: [
        {
          id: "u9-l1",
          order: 1,
          title: "Safari",
          activities: [
            {
              id: "u9-l1-a1",
              kind: "phonics-wordbuild",
              title: "Add an ending",
              blurb: "-s, -ed, -ing.",
              estMinutes: 9,
              band: "ready",
              skillTags: ["phonics.endings"],
              standardTags: ["CCSS.RF.1.3.f"],
              config: {
                focus: "inflectional endings -ing / -ed",
                instruction: "Add the ending to finish the word.",
                tiles: ["ing", "ed", "s", "jump", "play", "run"],
                words: [{ word: "jumping", picture: "🦘" }, { word: "played", picture: "🎮" }],
              },
            },
            {
              id: "u9-l1-a2",
              kind: "math-tenframe",
              title: "Share it fair",
              blurb: "Half of ten.",
              estMinutes: 7,
              band: "ready",
              skillTags: ["math.geometry"],
              standardTags: ["CCSS.1.G.3"],
              config: { instruction: "Ten animals, two dens. Show half in one frame.", mode: "represent", target: 5 },
            },
          ],
        },
      ],
    },
    {
      id: "u10",
      order: 10,
      title: "Maker Week & Showcase",
      emoji: "🛠️",
      world: "sunshine",
      bigIdea: "Put it all together. Count by groups, build arrays.",
      phonicsFocus: "Review + multisyllable words",
      mathFocus: "Skip-count 2s/5s/10s; arrays [2nd stretch]",
      project: "The Academy showcase",
      checkpoint: "final",
      lessons: [
        {
          id: "u10-l1",
          order: 1,
          title: "Showcase day",
          activities: [
            {
              id: "u10-l1-a1",
              kind: "sightword-game",
              title: "Word champion",
              blurb: "All the words you grew.",
              estMinutes: 7,
              band: "ready",
              skillTags: ["reading.sight-words", "habits.stamina"],
              config: { instruction: "Show off! Tap every word you can read.", words: ["because", "could", "should", "where", "there", "their"], decoys: ["becuz", "cud", "wair"] },
            },
            {
              id: "u10-l1-a2",
              kind: "math-tenframe",
              title: "Count by groups",
              blurb: "Skip-count by fives.",
              estMinutes: 8,
              band: "stretch",
              skillTags: ["math.skip-count"],
              standardTags: ["CCSS.2.NBT.2"],
              config: { instruction: "Fill by fives: 5, 10, 15! Show 15 on the frames.", mode: "represent", target: 15, frames: 2 },
            },
            {
              id: "u10-l1-a3",
              kind: "journal-prompt",
              title: "Look how I grew",
              blurb: "From June to August.",
              estMinutes: 10,
              band: "ready",
              skillTags: ["writing.sentence", "habits.stamina"],
              config: { prompt: "Draw something you can do now that was hard in June.", sentenceStarter: "Now I can…" },
            },
          ],
        },
      ],
    },
  ],
};
